### ISSUE TITLE
bug: Wezterm themes are just Tokyo night copy-pasted

### ISSUE THREAD

**Issue by nshern** [craftzdog/solarized-osaka.nvim#32] opened 2024-04-17 18:42 UTC
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2543+gade1b12f4-Homebrew

### Operating system/version

MacOS 14.4.1

### Describe the bug

Wezterm themes are just Tokyo night copy-pasted
https://github.com/craftzdog/solarized-osaka.nvim/tree/main/extras/wezterm

### Steps To Reproduce

1. Inspect the Wezterm themes
2. See metadata

### Expected Behavior

That they have the actual colorscheme

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by craftzdog** [comment] 2024-04-18 01:26
duplicate of https://github.com/craftzdog/solarized-osaka.nvim/pull/27

**Closed by craftzdog** 2024-04-18 01:26 UTC
Labels: bug
