### ISSUE TITLE
bug: extras/tmux themes are for tokyonight.nvim, not solarized osaka

### ISSUE THREAD

**Issue by theamallalgi** [craftzdog/solarized-osaka.nvim#54] opened 2024-12-18 19:30 UTC
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Windows 11, MacOS Sonoma

### Describe the bug

The Theme files inside Extras/Tmux, is for a theme called Tokyonight (Original Project Solarized Osaka was probably based on), and was not/is still not updated and refactored for Solarized Osaka's colors.

### Steps To Reproduce

- set up the theme on tmux
- notice the problem.

### Expected Behavior

The Themes inside should be for Solarized Osaka, the proposed colorscheme.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by Redoxahmii** [comment] 2024-12-23 11:15
Closing because it's a duplicate of #33.

**Closed by Redoxahmii** 2024-12-23 11:15 UTC
Labels: bug
